on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
          package-name: rolandbergergraph
          changelog-types: '[{"type": "feat", "section":"Features","hidden":false},{"type": "test", "section":"Test","hidden":false},{"type": "fix", "section":"Bug Fixes","hidden":false},{"type": "style", "section":"Styling","hidden":false},{"type": "refactor", "section":"Code Refactor","hidden":false},{"type": "docs", "section":"Doc","hidden":false},{"type": "chore", "section":"Chore","hidden":false}]'
      # Checkout
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      # Install dependencies
      - run: npm install
        if: ${{ steps.release.outputs.release_created }}
      # Build output
      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}
      # Publish to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
